// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuitSmoking.Repository.NamHH.Models;

public partial class SessionFeedbackNamHh
{
    public int SessionFeedbackNamHhid { get; set; }

    public int ConsultationSessionNamHhid { get; set; }

    public string FeedbackText { get; set; }

    public int Rating { get; set; }

    public DateTime? FeedbackDate { get; set; }

    public bool? IsResolved { get; set; }

    public string Response { get; set; }

    public DateTime? ResolvedDate { get; set; }

    public string Responder { get; set; }

    public bool FollowUpRequired { get; set; }

    public virtual ConsultationSessionNamHh ConsultationSessionNamHh { get; set; }
}